spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      bootstrap-servers: localhost:9092
      group-id: swa1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  # h2 DB
  datasource:
#    url: jdbc:h2:tcp://localhost/~/kafka
    url: jdbc:h2:mem:kafka
    username: swa1
    password:
    driver-class-name: org.h2.Driver

  # jpa 설정
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create